config/routes.rb
Rails.application.routes.draw do
  resources :thoughts

  root :to => "home#index"

  resource :stay_tuned do
    get "index"
end

end

app/models/thought.rb
class Thought < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/stay_tuned_controller.rb
class StayTunedController < ApplicationController

def index
end
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  before_action :set_thought, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @thoughts = Thought.all
    respond_with(@thoughts)
  end

  def show
    respond_with(@thought)
  end

  def new
    @thought = Thought.new
    respond_with(@thought)
  end

  def edit
  end

  def create
    @thought = Thought.new(thought_params)
    @thought.save
    respond_with(@thought)
  end

  def update
    @thought.update(thought_params)
    respond_with(@thought)
  end

  def destroy
    @thought.destroy
    respond_with(@thought)
  end

  private
    def set_thought
      @thought = Thought.find(params[:id])
    end

    def thought_params
      params.require(:thought).permit(:title, :tldr, :category, :preview, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stay_tuned_helper.rb
module StayTunedHelper
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <!-- Meta Data -->
  <title>Panashe Mahachi | Hacker and Entrepreneur</title>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="author" content="Panashe Mahachi">
  <meta name="Keywords" content="computer science, student, Panashe, Mahachi, junior achievement, moocs, software">
  <meta name="description" content="Panashe Mahachi, student at the University of Waterloo">
  
  <!-- jQuery-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" type=
  "text/javascript">
</script>

<!-- Bootstrap -->
<%= stylesheet_link_tag "custom", media: "all" %>
<%= stylesheet_link_tag "animations", media: "all" %>
<%= stylesheet_link_tag "bootstrap", media: "all" %>
<%= stylesheet_link_tag "bootstrap", media: "all" %>
<%= javascript_include_tag 'bootstrap.min', media: 'all'%>
  <%= javascript_include_tag 'modscript', media: 'all'%>

<!-- Font Awesome -->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">    
<!-- favicons -->
<link rel="icon" href="images/favicon.ico">
<link rel="apple-touch-icon" href="images/apple-touch-reg.png" />
<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-72x72.png" />
<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-114x114.png" />
<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-144x144.png" />

<!-- Analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-53148816-1', 'auto');
  ga('send', 'pageview');
</script>
</head>
<body data-spy="scroll" data-target=".collapse" data-offset-top="20"> 

 <!-- Navbar -->
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation" id="my-nav">
    <div class="container">
      <div class="navbar-header" >
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" >
          <div id="nav-icon1">
            <span></span>
            <span></span>
            <span></span>
          </div>
        </button>
          <!-- <a class="navbar-brand img-responsive" href="//pmahachi.com"><img src="../images/panashemahachi.png" /></a> -->
      </div>

      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right raleway" data-toggle="collapse" data-target=".navbar-collapse" id="menu"> 
          <li><a href="#hello"> hello</a></li>
          <li><a href="#About"> about</a></li>
          <li><a href="#Skills"> skills</a></li>
          <li><a href="#Portfolio">portfolio</a></li>
          <li><a href="#contactme">contact</a></li>
            <li><a href="resume.pdf" target="_blank">résumé</a></li>
          <li><%= link_to "blog", controller: "stay_tuned" %></li>
        </ul>
      </div>
    </div>
  </nav> <!-- end Navbar -->


<%= yield %>


              <!-- Footer -->
              <footer>
                <div class="container">
                  <div class="row">
                    <div class="col-sm-12 centimgs">
                        <a href="http://twitter.com/panashemahachi" target="_blank" class="
                          twitter"><%= image_tag "twitter.png", :class => "img-responsive"%></a>

                          <a href="http://linkedin.com/in/pmahachi" target="_blank" class=
                            "linedin"><%= image_tag "linedin.png", :class => "img-responsive"%></a>
                            <a href="https://github.com/panashemahachi" target="_blank" class=
                              "github"><%= image_tag "github.png", :class => "img-responsive"%></a>
                              <hr style="margin:0px;">
                              <small>by Panashe Mahachi with help from the <a href="http://getbootstrap.com">Twitter</a> crew</small>
                            
                          </div>           
                        </div>
                      </div>
                    </footer> <!-- end Footer -->
</body>
</html>

app/views/stay_tuned/index.html.erb
<h1> I love that you wanted to check out the blog.  I'm in the process of migrating all my posts to Rails...</h1>
<h6> Hurry up </h6>

app/views/thoughts/_form.html.erb
<%= form_for(@thought) do |f| %>
  <% if @thought.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thought.errors.count, "error") %> prohibited this thought from being saved:</h2>

      <ul>
      <% @thought.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-md-12">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field col-md-12">
    <%= f.label :tldr %><br>
    <%= f.text_field :tldr %>
  </div>
  <div class="field col-md-12">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field col-md-12">
    <%= f.label :preview %><br>
    <%= f.text_area :preview %>
  </div>
  <div class="field col-md-12 content">
    <%= f.label :content %><br>
    <%= f.text_area :content, :cols => "50", :rows =>"15"%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/thoughts/edit.html.erb
<h1>Editing thought</h1>

<%= render 'form' %>

<%= link_to 'Show', @thought %> |
<%= link_to 'Back', thoughts_path %>

app/views/thoughts/index.html.erb
<div class="container">
<h1 style="padding-top:60px">My Thoughts<small>right or wrong </small></h1>


    <% @thoughts.each do |thought| %>
    <div class="row">
        <h2><%= thought.title %></h2>
        <p class="lead well well-sm" style="margin:0px;">TLDR: &nbsp;<%= thought.tldr %></p>
        </div>
        <div class="row">
        <p style="margin:0px;"> Category: &nbsp;<span class="badge badge-info" ><%= thought.category %></span></p>
<hr style="margin:2px;">
        </div>
        <div class="row">
        <p><%= thought.preview %></p>
                
      
        <p><center><%= link_to 'Read More', thought %></center></p>
        </div>
        <%= link_to 'Edit', edit_thought_path(thought) %>
        <%= link_to 'Destroy', thought, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <% end %>
</div>



<%= link_to 'New Thought', new_thought_path %>

app/views/thoughts/new.html.erb
<h1>New thought</h1>

<%= render 'form' %>

<%= link_to 'Back', thoughts_path %>

app/views/thoughts/show.html.erb
<p id="notice"><%= notice %></p>



<div class="container">



    <div class="row">
    <h1 style="padding-top:60px">My Thoughts<small>right or wrong </small></h1>
        <h2> <%= @thought.title %></h2>
        <p class="lead well well-sm" style="margin:0px;">TLDR: &nbsp;<%= @thought.tldr %></p>
        </div>
        <div class="row">
        <p style="margin:0px;"> Category: &nbsp;<span class="badge badge-info" ><%= @thought.category %></span></p>
<hr style="margin:2px;">
        </div>
        <div class="row">
        <p><%= @thought.content %></p>
                </div>

        <%= link_to 'Edit', edit_thought_path(@thought) %> |
<%= link_to 'Back', thoughts_path %>
</div>